language: scala
sudo: false
scala:
  - 2.10.6
  - 2.11.8
jdk:
  - openjdk7
addons:
  hostname: localhost
matrix:
  include:
  - scala: 2.12.1
    jdk: oraclejdk8
  - scala: 2.13.0-M1
    jdk: oraclejdk8
